GET http://localhost:8080/user/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNvZ25pdG9Mb2NhbCJ9.eyJhdXRoX3RpbWUiOjE3MjQ3ODc3NTYsImNsaWVudF9pZCI6IjA2NjJseTdqd3Nibzg3bWJobnB6aHl1c3oiLCJldmVudF9pZCI6IjljM2Q3MTUxLTgwMTUtNDIyZS05MTIwLTUxMjA4NGQyOGQ4NCIsImlhdCI6MTcyNDc4Nzc1NiwianRpIjoiNTVhMzY5MGYtNWRiYi00ZTgxLWFlOWUtYjc3YTQ5MTk0NTA5Iiwic2NvcGUiOiJhd3MuY29nbml0by5zaWduaW4udXNlci5hZG1pbiIsInN1YiI6IjI0ODI0MjJkLWE3ZmMtNGMzNC04MTRiLWU1MzliN2I3NmQ5YiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiZnJ5IiwiY29nbml0bzpncm91cHMiOlsiQ09OU1VNRVJfQkFTSUMiXSwiZXhwIjoxNzI0ODc0MTU2LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkyMjkvbG9jYWxfMWY1a3RzN3kifQ.D0Gsh5jMfEyPOSzI8Ra_Ox1VMhvtpufWxCvjWXR-2y4zB9ACk4cVXlz-_lOA0OYjipUEo39wrd7-z4tDT9Iiz2_JyZXP2HDEndjVcY-H4yRoXHrjYIMoP6W7GP4tyx8Uccb8PDD7-HNBsu7q7c1svVuIg4VFTXgKv_RA7DsU5A2JcTXW0JQ19JtEDElntqt-W-JnUXc4yOn-alrCiNYtb-IStc8dmrlMzKy4jdi5WRCWVGwUFYXDqlt19qicWz2aMwAMrWacQqgtiPq9pAy1iwtrQMUCkIdU-oaVmmmnpC1EZfh36bOqPKj75B3B9K7oeIYJsi-4cyGCyDIpLxjiJA

###
GET http://localhost:8080/user/2482422d-a7fc-4c34-814b-e539b7b76d9b
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNvZ25pdG9Mb2NhbCJ9.eyJhdXRoX3RpbWUiOjE3MTU1NDY2NDcsImNsaWVudF9pZCI6IjA2NjJseTdqd3Nibzg3bWJobnB6aHl1c3oiLCJldmVudF9pZCI6Ijc0ZjRlZGM0LTZjNmQtNGExZi04OTY2LTgxMjgyNmY1NzU1ZSIsImlhdCI6MTcxNTU0NjY0NywianRpIjoiMjYwYjA3MDktYjFkMy00Yzk3LTg0YjYtNWYwZTRiOGQwN2IzIiwic2NvcGUiOiJhd3MuY29nbml0by5zaWduaW4udXNlci5hZG1pbiIsInN1YiI6IjI0ODI0MjJkLWE3ZmMtNGMzNC04MTRiLWU1MzliN2I3NmQ5YiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiZnJ5IiwiY29nbml0bzpncm91cHMiOlsiQ09OU1VNRVJfQkFTSUMiXSwiZXhwIjoxNzE1NjMzMDQ3LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkyMjkvbG9jYWxfMWY1a3RzN3kifQ.JlSXHuIm-2B_Gx3GI65iYjhyN2Toqq3EXp47buaqKTqorodueToMN2AdvpoCmPUBEQ72k3XUWI9l68TKxccUx0QNi7Jvgl-HE5CmgykpwKrvGfwMNVIuRhXN6B7GW906xa3JSDMPoMtJC4GTL3dCxUL3HIAAjZ9CFH8EQD-F6cY3Q__TtTCbF93srTFCPi9B_ZDaOw01teiQM1J-v6UJvl5HahqQxGZybGs_7SDi6Gq0F35i4Wc2zr7EJzvVliJW79USO13fhixsXl7AU-3QNLksukREaeu4nT2w5uelihPtD0vEjSQSG-17t45WpLymw1sbBo0fTZTPo2EzA_Geug
#Cookie: bk_acc=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNvZ25pdG9Mb2NhbCJ9.eyJhdXRoX3RpbWUiOjE2ODg2MjUwOTUsImNsaWVudF9pZCI6IjA2NjJseTdqd3Nibzg3bWJobnB6aHl1c3oiLCJldmVudF9pZCI6IjY0ZmJlYTY2LWE4NDUtNDAxZS1hMDY2LTYyNjdjZTEyYjA3NCIsImlhdCI6MTY4ODYyNTA5NSwianRpIjoiZTQxZTU3NDgtMTdkZi00MGQ4LWEwZDctZjg2ZjQ1ZmZhODEyIiwic2NvcGUiOiJhd3MuY29nbml0by5zaWduaW4udXNlci5hZG1pbiIsInN1YiI6IjI0ODI0MjJkLWE3ZmMtNGMzNC04MTRiLWU1MzliN2I3NmQ5YiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiYm9iIiwiZXhwIjoxNjg4NzExNDk1LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkyMjkvbG9jYWxfMWY1a3RzN3kifQ.tc_Vi2isKwT4ztAhCBoIvHPdUeMlZPcgM5flWzVv_1DnBORPQN_1Vy8AVlhigcOzXGr4cy_ZdXRAdSXhLet84we6DYAvZ9erT14odshEwQ5Vu_LbdPTfHXWQgIMgTAetXDUIJkyPtwwVgYXUlbXe3ksCgtg_uo8dU6c6uZux-UInjvccsgtK6-flS3JBkBjGTO0bKdPAdkjo9Ho9VSjzeTlmbcCHXLh-nkvpRTZakJ2jGW5KIOmRq6PI6zwZkk-JCA_rWMqyCVIniMiFrZMCxMp_rZtqzC-6cJHOlcpGHz6aqRX4mIX3V0KqZdh797UFmI7Ui24fx9KJobaGaHt-VA; Max-Age=31536000000; Domain=.qabackit.com; HttpOnly; SameSite=Strict
###

kyxku4-caqxid-rustyF
hawdoj-fyctAm-2nizco
macro-08-tries@icloud.com

GET http://localhost:3000/oauth/profile
Accept: application/json
#Cookie: bk_acc=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNvZ25pdG9Mb2NhbCJ9.eyJhdXRoX3RpbWUiOjE2ODg0Mjc3MzAsImNsaWVudF9pZCI6IjA2NjJseTdqd3Nibzg3bWJobnB6aHl1c3oiLCJldmVudF9pZCI6ImIzMzkzMGJhLTBkNjUtNGQ3NC04OGI4LWE5MzY0OTUzODNiYiIsImlhdCI6MTY4ODQyNzczMCwianRpIjoiMGEzMzA2ZTEtMWY0ZS00YWFlLTg3ODktMDUxOTRkMjMzMmFiIiwic2NvcGUiOiJhd3MuY29nbml0by5zaWduaW4udXNlci5hZG1pbiIsInN1YiI6IjU4ZDlmZjI2LTVhZDMtNGJhOC04ZDcxLTQ4YTc0YjU3ODQ4MSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiYm9iIiwiZXhwIjoxNjg4NTE0MTMwLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjkyMjkvbG9jYWxfMWY1a3RzN3kifQ.jdw05IV_yX9QB38ubieaFrOyLsNRxfDCTQb1sFNNg86YQAO6RK7qFmcAjKtgltGoup00WGyu-YtIR609p27UuBmDDg864C2zHKMPxfynvDLN804nvYk1FPAhWTegSEYUKIAU11ZdeU99YQ3PeH3E20OOc4CRQQBPCsqlXw26DmfYtVn4wL-nSt3Rgw6gm4B9h_F8nxDUTz2RTrBRTLdnMKj4gVa1-I9VCJmVy1l8bpHoGL4PhlEbLgu6QeuJTKEmGQr75GFI2ugd3Yj_e5omyompAed8WnYKBxZ44ILgWC5GjG3f0mwIkQ0NgYWwSrGCzK3AzqGHv2hdk7vIkyR-Rg; Max-Age=31536000000; Domain=.qabackit.com; HttpOnly; Secure; SameSite=Strict


###
POST http://localhost:3000/email/bob@gmail.com
Content-Type: application/json

{
  "email": "bob@gmail.com",
  "code": "9GFRZC"
}

###

POST http://localhost:8080/email
Content-Type: application/json

{
  "email": "britton@plymouthstreet.com"
}

###
POST http://localhost:8080/oauth/login
Content-Type: application/json

{
  "email": "phillip.j.fry@planetexpress.com",
  "password": "password"
}


###
POST http://localhost:3000/oauth/login
Content-Type: application/json

{
  "email": "bob@gmail.com"
}

###
GET http://localhost:3000/oauth/bob@gmail.com
Accept: application/json

###
GET http://localhost:3000/user/489f92ef-6b52-44dd-a3ff-fec5e320cfd7
Accept: application/json

###
POST http://localhost:3000/user
Content-Type: application/json

{
  "email": "bob@gmail.com",
  "userName": "bob",
  "password": "password"
}

###
GET http://localhost:3000/user
Content-Type: application/json

